// <auto-generated />
using System;
using CadeMedicoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadeMedicoAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CadeMedicoAPI.Models.CidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "PR",
                            Nome = "Londrina"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "PR",
                            Nome = "Maringa"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "PR",
                            Nome = "Apucarana"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "SP",
                            Nome = "Assai"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "SP",
                            Nome = "São Paulo"
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ortopedista"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Otorrinolaringologista"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ginecologita"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Cardiologista"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Oftalmologista"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Clínico Geral"
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.MedicoCidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("MedicoCidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            CidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            CidadeId = 5
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.MedicoEspecialidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("MedicoEspecialidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            EspecialidadeId = 2
                        },
                        new
                        {
                            MedicoId = 3,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            EspecialidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            EspecialidadeId = 5
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.MedicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "3645655",
                            Nome = "Marcos",
                            Telefone = "909090"
                        },
                        new
                        {
                            Id = 2,
                            Crm = "123456",
                            Nome = "Luiz",
                            Telefone = "404050"
                        },
                        new
                        {
                            Id = 3,
                            Crm = "098764",
                            Nome = "Joao",
                            Telefone = "201050"
                        },
                        new
                        {
                            Id = 4,
                            Crm = "501854",
                            Nome = "Guilherme",
                            Telefone = "778899"
                        },
                        new
                        {
                            Id = 5,
                            Crm = "439800",
                            Nome = "Joares",
                            Telefone = "1155335"
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.PrivilegioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Privilegios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Master"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ADM"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "USER"
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "marc",
                            Nome = "Marcos",
                            PrivilegioId = 1,
                            Senha = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Login = "carl",
                            Nome = "Carlos",
                            PrivilegioId = 2,
                            Senha = "1234"
                        },
                        new
                        {
                            Id = 3,
                            Login = "fern",
                            Nome = "fernando",
                            PrivilegioId = 3,
                            Senha = "1234"
                        },
                        new
                        {
                            Id = 4,
                            Login = "joao",
                            Nome = "joao",
                            PrivilegioId = 3,
                            Senha = "1234"
                        },
                        new
                        {
                            Id = 5,
                            Login = "jona",
                            Nome = "Jonathan",
                            PrivilegioId = 2,
                            Senha = "1234"
                        });
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.EspecialidadeModel", b =>
                {
                    b.HasOne("CadeMedicoAPI.Models.EspecialidadeModel", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.MedicoCidade", b =>
                {
                    b.HasOne("CadeMedicoAPI.Models.CidadeModel", "Cidade")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadeMedicoAPI.Models.MedicoModel", "Medico")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.MedicoEspecialidade", b =>
                {
                    b.HasOne("CadeMedicoAPI.Models.EspecialidadeModel", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadeMedicoAPI.Models.MedicoModel", "Medico")
                        .WithMany("MedicoEspecialidades")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.CidadeModel", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("CadeMedicoAPI.Models.MedicoModel", b =>
                {
                    b.Navigation("MedicoCidade");

                    b.Navigation("MedicoEspecialidades");
                });
#pragma warning restore 612, 618
        }
    }
}
